### ISSUE TITLE
Oracle Connectivity with PHP 7

### ISSUE THREAD

**Issue by whmemon** [sfedosimov/yii2-oci8pdo#3]
Hi,

I am using php 5.6.25 and Oracle 10.2.x R2. and doing every thing perfectly.

As i change my Wamp 3.0.6 to PHP 7.0.10 and enable OCI extension it gives error "This site can’t be reached"

I have checked all things related to network and not behind firewall.
![download](https://cloud.githubusercontent.com/assets/12655625/24799729/4ece2b5c-1bb6-11e7-821b-240ebcfca0b4.png)

Please see attachment.

**Comment by sarmadmahar** [comment]
I had same issue and found solution , you have to use below code in db.php, May be extension you are using is deprecated.

```
<?php
return [
    'class' => 'yii\db\Connection' ,
    'dsn' => 'oci:dbname=//192.168.20.132:1521/shcdb1', // Oracle
    'username' => 'cfmisis',
    'password' => 'cfmisis',
    'charset' => 'utf8' ,
];
?>
```

**Comment by whmemon** [comment]
Issue Resolved.  Also used PDO_OCI lib with above settings. 
Thanks Sarmad.
